### ISSUE TITLE
index.js file references

### ISSUE THREAD

**Issue by krkearney** [CABrouwers/node-red-contrib-telnet#1]
In a couple of your files you have the following lines which are causing issues when I try to use this:
const te = require("C:/Users/Charles-Andre.HOME/source/repos/telnet-engine/index.js")

telnet-send.js
telnet-request.js

**Comment by Nailik** [comment]
That should be the problem that causes those two nodes dissaperaing in my nodered.
![df](https://user-images.githubusercontent.com/13292441/98297879-68a33480-1fb5-11eb-88c1-dc57ea0d4fe9.JPG)

**Comment by CABrouwers** [comment]
Thanks for reporting these issues. I think I corrected both issues. Sorry for the trouble. Two months ago I split this project between a more generic node.js module (telnet-engine) and this node-red module.  Since i have used and refined the underlying telnet-engine module but haven't spent much time on the node-red version.
